admin:
  # For GRPC endpoints you might want to use dns:///flyte.myexample.com
  endpoint: dns:///development.uniondemo.run
  # Change insecure flag to ensure that you use the right setting for your environment
  insecure: false
  clientId: flytepropeller
  clientSecretLocation: /home/runner/secret_location
logger:
  # Logger settings to control logger output. Useful to debug logger:
  show-source: true
  level: 1
