apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal
  namespace: flyte
  labels:
    app: portal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portal
  template:
    metadata:
      labels:
        app: portal
    spec:
      containers:
      - name: portal
        image: ghcr.io/flyteorg/flyteportal:0.42.0
        command:
          - sleep
          - infinity
