name: Bump Version

on:
  workflow_call:
    outputs:
      version:
        description: "Tag name"
        value: ${{ jobs.bump_version.outputs.tag }}
    secrets:
      FLYTE_BOT_PAT:
        required: true
jobs:
  bump_version:
    name: Bump Version
    if: github.actor != 'goreleaserbot'
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.bump-version.outputs.tag }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - name: Set branch name
        id: extract_branch
        run: echo "::set-output name=branch_name::$(echo ${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}})"
      - name: Bump version and push tag
        id: bump-version
        uses: anothrNick/github-tag-action@1.34.0
        env:
          GITHUB_TOKEN: ${{ secrets.FLYTE_BOT_PAT }}
          WITH_V: true
          DEFAULT_BUMP: patch
          RELEASE_BRANCHES: ${{ steps.extract_branch.outputs.branch_name }}