name: Go Generate

on:
  workflow_call:
    inputs:
      go-version:
        default: "1.19"
        required: false
        type: string
jobs:
  generate:
    runs-on: ubuntu-latest
    name: Go Generate
    steps:
      - uses: actions/checkout@v3
      - uses: arduino/setup-protoc@v1
        with:
          repo-token: ${{ secrets.FLYTE_BOT_PAT }}
      - uses: bufbuild/buf-setup-action@v1
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ inputs.go-version }}
      - name: Go generate and diff
        run: DELTA_CHECK=true make generate
