name: Bump Version

on:
  workflow_call:
    inputs:
      version:
        description: "Release version"
        required: true
        type: string
      dry_run:
        description: "Dry Run"
        required: false
        type: boolean
    secrets:
      FLYTE_BOT_PAT:
        required: true
jobs:
  goreleaser:
    name: Goreleaser
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Dry Run
        id: extract_command
        run:|
          if [[ ${{ inputs.dry_run }} ]]
          then
            echo "::set-output name=command::'release'"
          else
            echo "::set-output name=command::'--snapshot  --skip-publish'"
          fi
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: ${{ steps.extract_command.outputs.command }} --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.FLYTE_BOT_PAT }}
          GORELEASER_CURRENT_TAG: ${{ inputs.version }}