name: Build & Push Docker Image

on:
  workflow_call:
    inputs:
      dockerfile:
        description: "Dockerfile name"
        required: true
        type: string
      version:
        description: "Version of image"
        required: true
        type: string
      repository:
        description: "Repository Name"
        required: false
        type: string
      push:
        description: "Push to registry"
        required: false
        type: boolean
    secrets:
      FLYTE_BOT_USERNAME:
        required: true
      FLYTE_BOT_PAT:
        required: true
jobs:
  push-github:
    name: Push to Github Registry
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: "${{ secrets.FLYTE_BOT_USERNAME }}"
          password: "${{ secrets.FLYTE_BOT_PAT }}"

      - name: Build and Push Docker Image to Github Registry
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ inputs.repository }}:latest
            ${{ inputs.repository }}:${{ github.sha }}
            ${{ inputs.repository }}:${{ inputs.version }}
          build-args: |
            --compress=true
          file: ${{ inputs.dockerfile }}

      - uses: actions-ecosystem/action-push-tag@v1
        if: ${{ inputs.push }}
        with:
          tag: ${{ steps.bump-semver.outputs.new_version }}
