name: Build & Push Docker Image

on:
  workflow_call:
    inputs:
      dockerfile:
        description: "Dockerfile name"
        required: true
        type: string
      version:
        description: "Version of image"
        required: true
        type: string
      repository:
        description: "Repository Name"
        required: false
        type: string
      push:
        description: "Push to registry"
        required: false
        type: boolean
    secrets:
      FLYTE_BOT_USERNAME:
        required: true
      FLYTE_BOT_PAT:
        required: true
jobs:
  push-github:
    name: Push to Github Registry
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - name: Push Docker Image to Github Registry
        uses: whoan/docker-build-with-cache-action@v5
        with:
          username: "${{ secrets.FLYTE_BOT_USERNAME }}"
          password: "${{ secrets.FLYTE_BOT_PAT }}"
          image_name: ${{ inputs.repository }}
          image_tag: latest,${{ github.sha }},${{ inputs.version }}
          push_git_tag: ${{ inputs.push }}
          dockerfile: ${{ inputs.dockerfile }}
          registry: ghcr.io
          build_extra_args: "--compress=true"